// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VonageSmsDashboard.Server;

namespace VonageSmsDashboard.Server.Migrations
{
    [DbContext(typeof(SmsContext))]
    partial class SmsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5");

            modelBuilder.Entity("VonageSmsDashboard.Shared.DeliveryReceiptModel", b =>
                {
                    b.Property<string>("MessageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MessageTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Msisdn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<string>("To")
                        .HasColumnType("TEXT");

                    b.HasKey("MessageId");

                    b.ToTable("Dlrs");
                });

            modelBuilder.Entity("VonageSmsDashboard.Shared.InboundSmsModel", b =>
                {
                    b.Property<string>("MessageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MessageTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Msisdn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.Property<string>("To")
                        .HasColumnType("TEXT");

                    b.HasKey("MessageId");

                    b.ToTable("InboundSms");
                });

            modelBuilder.Entity("VonageSmsDashboard.Shared.OutboundSms", b =>
                {
                    b.Property<string>("MessageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("From")
                        .HasColumnType("TEXT");

                    b.Property<string>("MessagePrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.Property<string>("To")
                        .HasColumnType("TEXT");

                    b.HasKey("MessageId");

                    b.ToTable("OutboundSms");
                });
#pragma warning restore 612, 618
        }
    }
}
